// lib/constants/verification.ts

import type { VerificationLevelInfo } from '@/lib/types/verification';

export const VERIFICATION_LEVELS: Record<string, VerificationLevelInfo> = {
  basic_seller: {
    level: 'basic_seller',
    name: 'Basic Seller',
    nameEs: 'Vendedor Verificado',
    badge: {
      id: 'badge-basic',
      name: 'Verified Seller',
      nameEs: 'Vendedor Verificado',
      type: 'verification',
      level: 'basic_seller',
      icon: '⭐',
      color: 'text-secondary-600',
      bgColor: 'bg-secondary-100',
      description: 'Basic identity verification completed',
      descriptionEs: 'Verificación básica de identidad completada',
      earnedAt: new Date(),
      verified: true,
    },
    requirements: [
      'Valid government ID',
      'Phone number verification',
      'Email verification',
      'Basic profile completion',
    ],
    requirementsEs: [
      'INE o identificación oficial válida',
      'Verificación de número telefónico',
      'Verificación de correo electrónico',
      'Perfil básico completado',
    ],
    benefits: ['Can list products for sale', 'Access to basic seller tools', 'Buyer messaging'],
    benefitsEs: [
      'Puede listar productos a la venta',
      'Acceso a herramientas básicas de vendedor',
      'Mensajería con compradores',
    ],
    commissionRate: 10,
    estimatedTime: '1-2 días',
    difficulty: 'easy',
  },

  verified_artisan: {
    level: 'verified_artisan',
    name: 'Verified Artisan',
    nameEs: 'Artesano Verificado',
    badge: {
      id: 'badge-artisan',
      name: 'Verified Artisan',
      nameEs: 'Artesano Verificado',
      type: 'verification',
      level: 'verified_artisan',
      icon: '🎨',
      color: 'text-accent-600',
      bgColor: 'bg-accent-100',
      description: 'Authentic artisan verified by Papalote Market',
      descriptionEs: 'Artesano auténtico verificado por Papalote Market',
      earnedAt: new Date(),
      verified: true,
    },
    requirements: [
      'Basic Seller verification complete',
      'Workshop/creation space photos (5+)',
      'Craft process video (1-3 min)',
      'Product photos showing technique',
      'Years of experience documented',
    ],
    requirementsEs: [
      'Verificación de Vendedor Básico completada',
      'Fotos del taller/espacio de creación (5+)',
      'Video del proceso artesanal (1-3 min)',
      'Fotos de productos mostrando técnica',
      'Años de experiencia documentados',
    ],
    benefits: [
      'Reduced commission: 8%',
      'Featured in "Verified Artisans" section',
      'Priority placement in search',
      'Verification badge on all listings',
      'Access to analytics dashboard',
    ],
    benefitsEs: [
      'Comisión reducida: 8%',
      'Destacado en sección "Artesanos Verificados"',
      'Prioridad en resultados de búsqueda',
      'Insignia de verificación en todos los listados',
      'Acceso a tablero de analíticas',
    ],
    commissionRate: 8,
    estimatedTime: '3-5 días',
    difficulty: 'medium',
  },

  master_artisan: {
    level: 'master_artisan',
    name: 'Master Artisan',
    nameEs: 'Maestro Artesano',
    badge: {
      id: 'badge-master',
      name: 'Master Artisan',
      nameEs: 'Maestro Artesano',
      type: 'verification',
      level: 'master_artisan',
      icon: '👑',
      color: 'text-primary-700',
      bgColor: 'bg-gradient-to-r from-accent-200 to-primary-200',
      description: 'Master craftsperson with exceptional heritage',
      descriptionEs: 'Maestro artesano con herencia excepcional',
      earnedAt: new Date(),
      verified: true,
    },
    requirements: [
      'Verified Artisan status',
      'Professional certifications or awards',
      'Heritage/cultural documentation',
      '3+ community vouches from verified artisans',
      '50+ sales with 4.8+ rating',
      'Demonstrated mastery of traditional techniques',
    ],
    requirementsEs: [
      'Estatus de Artesano Verificado',
      'Certificaciones profesionales o premios',
      'Documentación de herencia/patrimonio cultural',
      '3+ referencias de artesanos verificados',
      '50+ ventas con calificación 4.8+',
      'Maestría demostrada en técnicas tradicionales',
    ],
    benefits: [
      'Lowest commission: 5%',
      'Premium homepage placement',
      'Custom shop URL',
      'Featured in media/press',
      'Priority customer support',
      'Exclusive master artisan badge',
      'Invitation to special events',
    ],
    benefitsEs: [
      'Comisión más baja: 5%',
      'Colocación premium en página de inicio',
      'URL de tienda personalizada',
      'Destacado en medios/prensa',
      'Soporte prioritario al cliente',
      'Insignia exclusiva de maestro artesano',
      'Invitación a eventos especiales',
    ],
    commissionRate: 5,
    estimatedTime: '5-7 días',
    difficulty: 'hard',
  },

  certified_workshop: {
    level: 'certified_workshop',
    name: 'Certified Workshop',
    nameEs: 'Taller Certificado',
    badge: {
      id: 'badge-workshop',
      name: 'Certified Workshop',
      nameEs: 'Taller Certificado',
      type: 'verification',
      level: 'certified_workshop',
      icon: '🏭',
      color: 'text-secondary-700',
      bgColor: 'bg-secondary-100',
      description: 'Officially certified artisan workshop',
      descriptionEs: 'Taller artesanal oficialmente certificado',
      earnedAt: new Date(),
      verified: true,
    },
    requirements: [
      'Verified Artisan status',
      'Physical location verification',
      'Business registration (RFC)',
      'Operating licenses',
      'Safety certifications',
      'Cultural organization endorsement',
      'Employee documentation (if applicable)',
    ],
    requirementsEs: [
      'Estatus de Artesano Verificado',
      'Verificación de ubicación física',
      'Registro de negocio (RFC)',
      'Licencias de operación',
      'Certificaciones de seguridad',
      'Aval de organización cultural',
      'Documentación de empleados (si aplica)',
    ],
    benefits: [
      'Commission: 7%',
      'Bulk listing tools',
      'B2B marketplace access',
      'Wholesale order management',
      'Corporate gifting programs',
      'Priority in local searches',
    ],
    benefitsEs: [
      'Comisión: 7%',
      'Herramientas de listado masivo',
      'Acceso a mercado B2B',
      'Gestión de pedidos mayoristas',
      'Programas de regalos corporativos',
      'Prioridad en búsquedas locales',
    ],
    commissionRate: 7,
    estimatedTime: '7-10 días',
    difficulty: 'hard',
  },
};

export const CRAFT_TYPES = [
  { value: 'ceramica', label: 'Cerámica', labelEn: 'Ceramics' },
  { value: 'textiles', label: 'Textiles', labelEn: 'Textiles' },
  { value: 'joyeria', label: 'Joyería', labelEn: 'Jewelry' },
  { value: 'madera', label: 'Madera', labelEn: 'Woodwork' },
  { value: 'vidrio', label: 'Vidrio', labelEn: 'Glasswork' },
  { value: 'metalurgia', label: 'Metalurgia', labelEn: 'Metalwork' },
  { value: 'talabarteria', label: 'Talabartería', labelEn: 'Leatherwork' },
  { value: 'papel', label: 'Papel', labelEn: 'Papercraft' },
  { value: 'pintura', label: 'Pintura', labelEn: 'Painting' },
  { value: 'escultura', label: 'Escultura', labelEn: 'Sculpture' },
  { value: 'otro', label: 'Otro', labelEn: 'Other' },
];

export const TRADITIONAL_TECHNIQUES = [
  { value: 'torno', label: 'Torno', labelEn: 'Pottery Wheel' },
  { value: 'telar', label: 'Telar', labelEn: 'Loom Weaving' },
  { value: 'pintado_mano', label: 'Pintado a Mano', labelEn: 'Hand Painting' },
  { value: 'tallado', label: 'Tallado', labelEn: 'Carving' },
  { value: 'fundicion', label: 'Fundición', labelEn: 'Casting' },
  { value: 'repujado', label: 'Repujado', labelEn: 'Embossing' },
  { value: 'vidrio_soplado', label: 'Vidrio Soplado', labelEn: 'Glassblowing' },
  { value: 'filigrana', label: 'Filigrana', labelEn: 'Filigree' },
  { value: 'bordado', label: 'Bordado', labelEn: 'Embroidery' },
  { value: 'macrame', label: 'Macramé', labelEn: 'Macramé' },
];

export const PRODUCTION_CAPACITY = [
  { value: 'small', label: '1-10 unidades/mes', labelEn: '1-10 units/month' },
  { value: 'medium', label: '11-50 unidades/mes', labelEn: '11-50 units/month' },
  { value: 'large', label: '50+ unidades/mes', labelEn: '50+ units/month' },
];

export const FILE_UPLOAD_LIMITS = {
  maxFileSize: 10 * 1024 * 1024,
  maxFiles: {
    photos: 10,
    videos: 3,
    documents: 5,
  },
  acceptedFormats: {
    photos: ['image/jpeg', 'image/png', 'image/webp'],
    videos: ['video/mp4', 'video/quicktime'],
    documents: ['application/pdf', 'image/jpeg', 'image/png'],
  },
};

export const STATUS_MESSAGES = {
  draft: {
    title: 'Borrador',
    description: 'Completa tu solicitud de verificación',
    color: 'text-gray-600',
    bgColor: 'bg-gray-100',
  },
  submitted: {
    title: 'Enviada',
    description: 'Tu solicitud está en la cola de revisión',
    color: 'text-secondary-600',
    bgColor: 'bg-secondary-100',
  },
  under_review: {
    title: 'En Revisión',
    description: 'Estamos revisando tu documentación',
    color: 'text-accent-600',
    bgColor: 'bg-accent-100',
  },
  info_requested: {
    title: 'Información Solicitada',
    description: 'Necesitamos documentos adicionales',
    color: 'text-primary-600',
    bgColor: 'bg-primary-100',
  },
  approved: {
    title: '¡Aprobada!',
    description: 'Felicidades, eres un vendedor verificado',
    color: 'text-green-600',
    bgColor: 'bg-green-100',
  },
  rejected: {
    title: 'No Aprobada',
    description: 'Revisa los motivos y vuelve a aplicar',
    color: 'text-red-600',
    bgColor: 'bg-red-100',
  },
  expired: {
    title: 'Expirada',
    description: 'Tu solicitud ha expirado, aplica de nuevo',
    color: 'text-gray-600',
    bgColor: 'bg-gray-100',
  },
};
